### ISSUE TITLE
How to get bilingual dictionary?

### ISSUE THREAD

**Issue by liujia1129** [facebookresearch/MUSE#103]
Hi all,
I'm trying to use MUSE to create an en-zh dictionary, but after finishing the training process(I think it finished, because I saw no more files generated and no more information in train.log file), it only give me these files:
1. two vector files: vectors-en.txt, vectors-zh.txt
2.best-mapping.pth
3.train.log
4.params.pkl
I wonder whether I could get the bilingual dictionary automatically after training finished? if not, how can I get the dictionary and how can I know the training is completed?
looking forward to your reply. Thanks~

**Comment by iamgroot42** [comment]
Any answers on this would be great. We could use extend the demo.ipynb notebook to assign word mappings in a greedy fashion, but that will be obviously sub-optimal, and won't scale with the dictionary size. Is there any other way around it>

**Comment by liujia1129** [comment]
Thank u~
