### ISSUE TITLE
Arrival BucketName does not exist (Multilingual aligned word vectors URLs broken)

### ISSUE THREAD

**Issue by dibesa** [facebookresearch/MUSE#105]
Hi all, 

I'm trying to download multilingual aligned word embeddings, but the URLs provided (for example, in the English case, https://s3.amazonaws.com/arrival/embeddings/wiki.multi.en.vec) doesn't work. Such URL just returns an XML code with the error:

`<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>arrival</BucketName>
    <RequestId>F8032D0C9093BD40</RequestId>   <HostId>mKnsh7BRQm438bb4B76aDEjwWz0e40ouNP2CZaVniosKY5jhZXdcBFFWAPFd6jchtG0qDsh4kZI=</HostId>
</Error>` 

And trying the download with wget:
`Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.83.67
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.83.67|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-31 12:03:44 ERROR 404: Not Found.`

Is there any alternative URL? Looking forward to your reply.

Thanks!

**Comment by glample** [comment]
Hi,

Sorry about that. This repo where we uploaded our embeddings / dictionaries has been deactivated, we need to upload them somewhere else. Will try to do this as soon as possible.

**Comment by glample** [comment]
Should be fixed. Does it work for you now?
