### ISSUE TITLE
The difference between fasttext aligned word vectors

### ISSUE THREAD

**Issue by 1049451037** [facebookresearch/MUSE#109]
Hi, I noticed that fasttext also released a set of [cross-lingual word vectors](https://fasttext.cc/docs/en/aligned-vectors.html). So which one is better to use?

**Comment by glample** [comment]
Ah, yes. The set of fastText word vectors is better, but this was trained in a supervised way. If you use it it should give better results.

**Comment by 1049451037** [comment]
OK, thanks!
