### ISSUE TITLE
Out-of-Vocabulary words in released models

### ISSUE THREAD

**Issue by matus-pikuliak** [facebookresearch/MUSE#13]
Hey,

is there any token for OOV words in released models? If I understand correctly, the projection is working with finite set of word embeddings, not with the fastText model itself. So there is no way to use the original fastText way to deal with OOV, right?

**Comment by matus-pikuliak** [comment]
Oh right, that makes sense, thanks. I will check it out.

**Comment by jensdebruijn** [comment]
I am wondering how to use the previously trained mapping to project a new embedding

Thanks!

**Comment by Nokeli** [comment]
> I am wondering how to use the previously trained mapping to project a new embedding
> 
> Thanks!
> 
> edit:
> 
> Nvm, got it!
> 
> ```
> mapping = torch.nn.Linear(300, 300, bias=False)
> to_reload = torch.from_numpy(torch.load('best_mapping.pth'))
> mapping.weight.data.copy_(to_reload.type_as(mapping.weight.data))
> translated_vector = mapping(vector)
> ```

can you send you code to me
