### ISSUE TITLE
Why do we get different embeddings for target language?

### ISSUE THREAD

**Issue by sbmaruf** [facebookresearch/MUSE#14]
According to the paper, the only trainable parameter is W, which is used to convert the source embeddings to the target ones. But, why the target embeddings are generated in a separate file, which are apparently different from the initial target embeddings?

**Comment by glample** [comment]
If the target embeddings in the generated source file are different, it can be for 2 reasons:
1) You set the parameter `normalize_embeddings` to something that will renormalize the loaded embeddings (either recenter them / divide them by their norm, etc) so they will be modified
2) The embeddings are normalized before they are written to the disk at the end of the experiment. 

Now that you are mentioning this I'm not sure we were right about 2), it might not be best for downstream tasks. A simple fix is simply to uncomment these 2 lines:
https://github.com/facebookresearch/MUSE/blob/master/src/trainer.py#L249-L250
After this, you should obtain the original embeddings on the target side.

**Comment by sbmaruf** [comment]
I just checked now. Thanks, @glample . You are right. This is happening because of the normalization.

**Comment by sbmaruf** [comment]
Hi @glample, Sorry to knock you again.
The default tags for --normalize_embeddings is set to ""(null). I was wondering, what is the importance of this?  what is your opinion about normalizing the embeddings? Why and When should we do this? I didn't find much about this in the paper.

Another thing which may not be a big deal,
In the README file, "The unsupervised way: adversarial training and refinement (CPU|GPU)" section, the command is,

> python unsupervised.py --src_lang en --tgt_lang es --src_emb data/wiki.en.vec --tgt_emb data/wiki.es.vec

whereas the default tag for --refinement in the source code is False. It would be great if you add to change the default section of the  --refinement tag or add the argument in the python call.

**Comment by bboczeng** [comment]
sorry, what are the two lines to be uncommented?  https://github.com/facebookresearch/MUSE/blob/master/src/trainer.py#L249-L250 has been changed since your comment

**Comment by glample** [comment]
These two https://github.com/facebookresearch/MUSE/blob/master/src/trainer.py#L255-L256

**Comment by bboczeng** [comment]
> These two https://github.com/facebookresearch/MUSE/blob/master/src/trainer.py#L255-L256

thx for the confirmation. Will comment those
