### ISSUE TITLE
Do you have chinese word embeddings?

### ISSUE THREAD

**Issue by 15091444119** [facebookresearch/MUSE#15]

**Comment by aconneau** [comment]
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

You can find here:
Traditional Chinese embeddings ("Chinese", number of signs: 332647)
Model Chinese embeddings ("Classical Chinese", number of signs: 10696)

Note that our dictionary en-zh is for Traditional Chinese.
