### ISSUE TITLE
Questions about the way to take use of the word embeddings.

### ISSUE THREAD

**Issue by yudianer** [facebookresearch/MUSE#19]
Hi, @glample 
Here is the output during the training progress. And I find these files(**best_mapping.t7  params.pkl  train.log  vectors-latin.txt  vectors-zh.txt**) in the dumped folder. But how could I take use of these word embeddings? Now, I am just taking a word's vector in source word embedding file and find top 10 words most similar to this vector in the target word embedding file. But is this way right?  Below outputs show there are two methods, namely nn and csls_knn_10, is it necessary to take care about these two methods? Thank you! 

==============================================
OrderedDict([('n_iter', 149)])
nn
path:data/crosslingual/dictionaries/zh-latin.5000-6500.txt
INFO - 01/24/18 09:18:02 - 1:28:43 - Found 8552 pairs of words in the dictionary (8552 unique). 9297 other pairs contained at least one unknown word (4953 in lang1, 6954 in lang2)
INFO - 01/24/18 09:18:02 - 1:28:43 - 8552 source words - nn - Precision at k = 1: 10.289991
INFO - 01/24/18 09:18:02 - 1:28:43 - 8552 source words - nn - Precision at k = 5: 17.516370
INFO - 01/24/18 09:18:02 - 1:28:44 - 8552 source words - nn - Precision at k = 10: 21.246492
csls_knn_10
path:data/crosslingual/dictionaries/zh-latin.5000-6500.txt
INFO - 01/24/18 09:18:02 - 1:28:44 - Found 8552 pairs of words in the dictionary (8552 unique). 9297 other pairs contained at least one unknown word (4953 in lang1, 6954 in lang2)
INFO - 01/24/18 09:18:05 - 1:28:46 - 8552 source words - csls_knn_10 - Precision at k = 1: 9.985968
INFO - 01/24/18 09:18:05 - 1:28:46 - 8552 source words - csls_knn_10 - Precision at k = 5: 16.300281
INFO - 01/24/18 09:18:05 - 1:28:47 - 8552 source words - csls_knn_10 - Precision at k = 10: 20.053789
INFO - 01/24/18 09:18:10 - 1:28:51 - Building the train dictionary ...
INFO - 01/24/18 09:18:10 - 1:28:51 - New train dictionary of 7721 pairs.
INFO - 01/24/18 09:18:10 - 1:28:51 - Mean cosine (nn method, S2T build, 10000 max size): 0.49470
INFO - 01/24/18 09:18:24 - 1:29:05 - Building the train dictionary ...
INFO - 01/24/18 09:18:24 - 1:29:05 - New train dictionary of 6263 pairs.
INFO - 01/24/18 09:18:24 - 1:29:05 - Mean cosine (csls_knn_10 method, S2T build, 10000 max size): 0.50656
INFO - 01/24/18 09:18:24 - 1:29:05 - __log__:{"n_iter": 149, "precision_at_1-nn": 10.28999064546305, "precision_at_5-nn": 17.516370439663238, "precision_at_10-nn": 21.246492048643592, "precision_at_1-csls_knn_10": 9.985968194574369, "precision_at_5-csls_knn_10": 16.300280636108514, "precision_at_10-csls_knn_10": 20.053788587464922, "mean_cosine-nn-S2T-10000": 0.49470236897468567, "mean_cosine-csls_knn_10-S2T-10000": 0.5065571665763855}
INFO - 01/24/18 09:18:24 - 1:29:05 - End of refinement iteration 149.

**Comment by aconneau** [comment]
NN (= Cosine Similarity) and CSLS (Cross-domain Similarity Local Scaling) are two measures of similarity between word vectors. If you have a source word in (say) Chinese, and you want to get its nearest neighbor in Latin, you may simply use the cosine similarity for simplicity (computing the cosine similarity with all the target words and retrieving the one with maximum similarity). For all the pairs that we have tried, CSLS provides better translation accuracy than cosine similarity, but also requires more computation. In your particular case it seems the results on word translation for NN or CSLS are similar, so you can safely use cosine similarity for your case. Note than Chinese-Latin is a difficult language pair (hence your 10% accuracy). Be particularly careful of the quality of your word embeddings in Latin.
