### ISSUE TITLE
readme should mention easy install of faiss

### ISSUE THREAD

**Issue by soumith** [facebookresearch/MUSE#2]
Faiss can now be installed using:

```
conda install faiss-cpu -c pytorch
# OR
conda install faiss-gpu -c pytorch
```

**Comment by kumarivin** [comment]
this command is not working for me, I am getting the following error , any advise please

`Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - faiss-cpu

Current channels:

  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch


INFO: deactivate_clangxx_osx-64.sh made the following environmental changes:
-CLANGXX=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-clang++
-CXX=x86_64-apple-darwin13.4.0-clang++
-CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0
-DEBUG_CXXFLAGS=-Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none
INFO: deactivate_clang_osx-64.sh made the following environmental changes:
-AR=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ar
-AS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-as
-CC=x86_64-apple-darwin13.4.0-clang
-CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
-CHECKSYMS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-checksyms
-CLANG=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-clang
-CODESIGN_ALLOCATE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-codesign_allocate
-CPPFLAGS=-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9
-DEBUG_CFLAGS=-Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none
-INDR=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-indr
-INSTALL_NAME_TOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-install_name_tool
-LD=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ld
-LDFLAGS=-pie -headerpad_max_install_names
-LDFLAGS_CC=-Wl,-pie -Wl,-headerpad_max_install_names
-LIBTOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-libtool
-LIPO=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-lipo
-NM=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-nm
-NMEDIT=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-nmedit
-OTOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-otool
-PAGESTUFF=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-pagestuff
-RANLIB=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ranlib
-REDO_PREBINDING=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-redo_prebinding
-SEGEDIT=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-segedit
-SEG_ADDR_TABLE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-seg_addr_table
-SEG_HACK=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-seg_hack
-SIZE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-size
-STRINGS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-strings
-STRIP=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-strip
INFO: activate_clang_osx-64.sh made the following environmental changes:
+AR=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ar
+AS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-as
+CC=x86_64-apple-darwin13.4.0-clang
+CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
+CHECKSYMS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-checksyms
+CLANG=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-clang
+CODESIGN_ALLOCATE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-codesign_allocate
+CPPFLAGS=-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9
+DEBUG_CFLAGS=-Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none
+INDR=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-indr
+INSTALL_NAME_TOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-install_name_tool
+LD=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ld
+LDFLAGS=-pie -headerpad_max_install_names
+LDFLAGS_CC=-Wl,-pie -Wl,-headerpad_max_install_names
+LIBTOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-libtool
+LIPO=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-lipo
+NM=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-nm
+NMEDIT=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-nmedit
+OTOOL=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-otool
+PAGESTUFF=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-pagestuff
+RANLIB=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-ranlib
+REDO_PREBINDING=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-redo_prebinding
+SEGEDIT=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-segedit
+SEG_ADDR_TABLE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-seg_addr_table
+SEG_HACK=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-seg_hack
+SIZE=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-size
+STRINGS=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-strings
+STRIP=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-strip
INFO: activate_clangxx_osx-64.sh made the following environmental changes:
+CLANGXX=/Users/***/anaconda3/envs/anacondav1/bin/x86_64-apple-darwin13.4.0-clang++
+CXX=x86_64-apple-darwin13.4.0-clang++
+CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0
+DEBUG_CXXFLAGS=-Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none`
