### ISSUE TITLE
Is translation dictionary required in unsupervised alignment?

### ISSUE THREAD

**Issue by fallingstar621** [facebookresearch/MUSE#21]
Hi, I was trying to train an alignment of embeddings from German to Japanese. Since we don't have a translation dictionary from German to Japanese, I was using unsupervised alignment, assuming no German2Japanese dictionary is required. However, during training, "unsupervised.py" calls the functions "evaluator.all_eval" and "self.word_translation" from "evaluator.py" and "word_translation.py" when it tries to do embeddings / discriminator evaluation, and the program stopped because no German2Japanese dictionary is found. I wonder whether in this case a translation dictionary is still required to perform unsupervised alignment, or is there any parameter I need to change to avoid this?

**Comment by glample** [comment]
Yes, by default we have a dictionary even in the unsupervised case, to check the quality of the model. You can disable the word retrieval evaluation by commenting out this line:
https://github.com/facebookresearch/MUSE/blob/master/src/evaluation/evaluator.py#L190
This should fix the issue, although you won't have feedback about the quality of your alignment during the training.

**Comment by fallingstar621** [comment]
@glample thank you for the clarification!
