### ISSUE TITLE
Why only First 200,000 vocab selected?

### ISSUE THREAD

**Issue by sbmaruf** [facebookresearch/MUSE#22]
According to the code,
https://github.com/facebookresearch/MUSE/blob/master/src/utils.py#L293

`unsupervised.py` only takes `200,000(by default)`/`restricted number of vocabulary` words from the embedding text file. 

From paper 'Word Translation without parallel data' section 3.2,

> The embedding quality of rare words is generally not as good as the one of frequent words and we observed that feeding discriminator with rare words had a small but not negligible negative impact.

What are the parameters you have added to handle this issue?

-  params.**max_vocab**
-  param.**dis_most_frequent**

from the given name it seems `param.dis_most_frequent` handles the issue but in that case, why did we restrict the total number of vocabulary by `params.max_vocab`.

**Comment by glample** [comment]
`max_vocab` is mostly here for debugging and convenience purposes. If you have an embedding file with 5,000,000 word embeddings, you don't want to load it during prototyping. Although, you can decide that for downstream tasks, it's enough to export aligned embeddings for the 200k most frequent words in each language.

`dis_most_frequent` has to be smaller than `max_vocab`, and is what the comment in section 3.2 is referring to.

**Comment by sbmaruf** [comment]
Thanks, @glample  for the clarification.
