### ISSUE TITLE
Discriminator inputs: frequency cutoff

### ISSUE THREAD

**Issue by YovaKem** [facebookresearch/MUSE#25]
I am having a hard time figuring out what embeddings to train the model on. Your paper says: "As a result, we only feed the discriminator with the 50,000 most frequent words."
Does that mean that input files data/wiki.en.vec and data/wiki.es.vec each contain 50,000 words only? 
If so, how do you then include 200,000 words in the experiments if output files data/wiki.en-es.en.vec and data/wiki.en-es.es.vec only contain 50,000 words each?

**Comment by glample** [comment]
No, the input files can contain as many words as you want. The output files will contain as many embeddings as the input files.
50,000 is just a parameter to limit the number of embeddings we train the discriminator on.

**Comment by YovaKem** [comment]
Okay, thank you. I just noticed the --dis_most_frequent parameter which I had previously missed.
