### ISSUE TITLE
Are the EN embeddings the same as the fastText EN embeddings normalized?

### ISSUE THREAD

**Issue by ronlut** [facebookresearch/MUSE#26]
I was wondering whether the English multilingual word embeddings are just a **normalized** subset (200K) of the fastText English embeddings?
I can see that the vectors are different between the two, would be happy to know if the reason is normalization or something else :)
Thanks!

**Comment by glample** [comment]
Yes, the English embeddings will be the same as the normalized fastText embeddings. We realized later that the normalization can be a bit detrimental so we will probably remove it soon. If you comment out these 2 lines:
https://github.com/facebookresearch/MUSE/blob/master/src/trainer.py#L249-L250
then the source embeddings should not be modified.

**Comment by ronlut** [comment]
All clear, thank you :)
