### ISSUE TITLE
"AssertionError" at end of processing word embedding [Unsupervised.py]

### ISSUE THREAD

**Issue by naman-agrawal** [facebookresearch/MUSE#27]
I tried to run the default data and program instructions for "Word translation without parallel data"
for En<--->Es language pairs
@glample 
**Why am I getting these errors in the end of the processing running unsupervised.py ?**
**(Errors are mentioned in the attachments.)**

![screenshot from 2018-02-27 22-53-28](https://user-images.githubusercontent.com/36732381/36798247-1f23a316-1cd0-11e8-9836-e1a53753498d.png)

![screenshot from 2018-02-27 23-33-02](https://user-images.githubusercontent.com/36732381/36798221-08ba7a78-1cd0-11e8-8844-aac11c09ee15.png)

**Comment by glample** [comment]
It looks like you did not download the evaluation data.
Did you run `./get_evaluation.sh` in the `data` folder before you start the experiment?

**Comment by naman-agrawal** [comment]
Oh! It seems that I skipped that step .
The problem stands solved.
Thank you !
