### ISSUE TITLE
How to open/view the best_mapping.t7 file?

### ISSUE THREAD

**Issue by naman-agrawal** [facebookresearch/MUSE#29]
I trained the model using unsupervised.py,
English<---->Spanish pair .
But I am unable to open best_mapping.t7 file.
What I know is it's a torch 7 file format, but I am unable to open/view it?

**Comment by glample** [comment]
Hi,
Sorry actually we made a mistake here, the extension should not be `.t7`, but `.pth`. It's a PyTorch binarized file. You can load it in Python with `torch.load(filepath)`.

**Comment by naman-agrawal** [comment]
Thanks!
Issue is resolved.
