### ISSUE TITLE
DIC_EVAL_PATH in word_translation sticks in the default path

### ISSUE THREAD

**Issue by transfluxus** [facebookresearch/MUSE#3]
wow, just working with it and you change so much of the readme and actually provide embeddings of 30 languages in one space! 
Fantastic, Thank you!

I was about to ask you how it would be possible to have more then 2 languages in 1 space on how accurate that still is.

One problem I encountered is that  `DIC_EVAL_PATH` in `src/evaluation/word_translation.py` is not changeable with an argument, so it would always look in the `default` path for it... 
Maybe another argument for that path or just one path parameter and it looks for `train.txt` and `eval.txt` or `src_lang-tgt_lang-train.txt`, ...

**Comment by glample** [comment]
Yes, having an optional path for the dictionary is a good idea, thank you for the suggestion! We will add this soon.

**Comment by gartentrio** [comment]
If you make DIC_EVAL_PATH configurable it would be great if you could also allow dictionaries to contain upper-case words. I have manipulated the dictionaries to fit my word embeddings (which are not lower-cased), and get an  error due to an assertion in word_translation.py:

```
/opt/muse/src/evaluation/word_translation.py in load_dictionary(path, word2id1, word2id2)
     56     with open(path, 'r') as f:
     57         for _, line in enumerate(f):
---> 58             assert line == line.lower()
     59             word1, word2 = line.rstrip().split()
     60             if word1 in word2id1 and word2 in word2id2:

AssertionError: 
```

**Comment by yudianer** [comment]
` python unsupervised.py --src_lang zh --tgt_lang mn --src_emb ~/models/vecs/zh-1220.vec.zh --tgt_emb ~/models/vecs/mn.vec.mn --dico_method nn`
when I use this method, there is an error:   assert mf <= min(len(self.src_dico), len(self.tgt_dico))

**Comment by glample** [comment]
Now there is an option to specify another evaluation dictionary: https://github.com/facebookresearch/MUSE/commit/27e193a93a6cef74601a64e249434658ef0d2338

**Comment by xzc721** [comment]
> If you make DIC_EVAL_PATH configurable it would be great if you could also allow dictionaries to contain upper-case words. I have manipulated the dictionaries to fit my word embeddings (which are not lower-cased), and get an error due to an assertion in word_translation.py:
> 
> ```
> /opt/muse/src/evaluation/word_translation.py in load_dictionary(path, word2id1, word2id2)
>      56     with open(path, 'r') as f:
>      57         for _, line in enumerate(f):
> ---> 58             assert line == line.lower()
>      59             word1, word2 = line.rstrip().split()
>      60             if word1 in word2id1 and word2 in word2id2:
> 
> AssertionError: 
> ```

could you tell me how to solve this problem?

**Comment by glample** [comment]
The lowercased dictionaries can handle the non-lowercased embeddings. The idea is the following: if for instance "london" is in the dictionary, and both "london" and "London" are in the embeddings, the model will use the embedding of the most frequent word between "london" and "London". In fastText, the words are sorted by decreasing frequency, so "London" will be the selected embeddings, which is probably what we want to have.

**Comment by xzc721** [comment]
This problem has been solved, thank you！！！
