### ISSUE TITLE
Error in dico_buildr.py, ValueError: result of slicing is an empty tensor

### ISSUE THREAD

**Issue by ChangXu-O-O** [facebookresearch/MUSE#31]
Hi, I was trying your method on the unsupervised setting, with en-fr language pair. I trained my embedding model using fastText on newstest 2014. Dictionary sizes of en and fr are 1962 and 2018.
I downloaded your ground-truth dictionary of en-fr full set, and put it on /MUSE/data/crosslingual/dictionaries/, and renamed it as "en-fr.5000-6500.txt". 

I used the following command:
python unsupervised.py --src_lang en --tgt_lang fr --src_emb ../fastText-0.1.0/myemb/en.tok.vec --tgt_emb ../fastText-0.1.0/myemb/fr.tok.vec --dis_most_frequent 1000

And then I got the following logs and error. Could you please help me with that? Thanks!

===========================================================

INFO - 03/22/18 03:15:36 - 0:07:24 - 996000 - Discriminator loss: 1.5441 - 4455 samples/s
INFO - 03/22/18 03:15:38 - 0:07:25 - Found 1335 pairs of words in the dictionary (1014 unique) 111951 other pairs contained at least one unknown word (109965 in lang1, 110720 in lang2)
INFO - 03/22/18 03:15:38 - 0:07:25 - 1014 source words - nn - Precision at k = 1: 0.098619
INFO - 03/22/18 03:15:38 - 0:07:26 - 1014 source words - nn - Precision at k = 5: 0.295858
INFO - 03/22/18 03:15:38 - 0:07:26 - 1014 source words - nn - Precision at k = 10: 0.493097
INFO - 03/22/18 03:15:39 - 0:07:26 - Found 1335 pairs of words in the dictionary (1014 unique) 111951 other pairs contained at least one unknown word (109965 in lang1, 110720 in lang2)
INFO - 03/22/18 03:15:39 - 0:07:26 - 1014 source words - csls_knn_10 - Precision at k = 1: 0.00000
INFO - 03/22/18 03:15:39 - 0:07:26 - 1014 source words - csls_knn_10 - Precision at k = 5: 0.43097
INFO - 03/22/18 03:15:39 - 0:07:26 - 1014 source words - csls_knn_10 - Precision at k = 10: 0.91716
Traceback (most recent call last):
  File "unsupervised.py", line 135, in <module>
    evaluator.all_eval(to_log)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/evaluationevaluator.py", line 192, in all_eval
    self.dist_mean_cosine(to_log)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/evaluationevaluator.py", line 172, in dist_mean_cosine
    s2t_candidates = get_candidates(src_emb, tgt_emb, _params)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/dico_buildr.py", line 38, in get_candidates
    scores = emb2.mm(emb1[i:min(n_src, i + bs)].transpose(0, 1)).transpose(0, 1)
ValueError: result of slicing is an empty tensor

**Comment by glample** [comment]
Can you try to add above this line:
https://github.com/facebookresearch/MUSE/blob/8c41b2e8050cabc0b3d65a6699e8fb0eb151b862/src/dico_builder.py#L38
This: `print(i, n_src, bs)`, then run it again and copy paste the output?

**Comment by ChangXu-O-O** [comment]
(1) I paste the output below. Please have a check. It seems that n_src is fixed to 10000, but my dictionary size is 1962 actually. How can I fix this?
(2) "/MUSE/data/crosslingual/dictionaries/en-fr.5000-6500.txt" is missing during run time, so I downloaded a dictionary and renamed it as "en-fr.5000-6500.txt". But I am not sure whether I am doing the right thing. Where can I get "en-fr.5000-6500.txt" and what is it for?

Thanks!

==========================
 
INFO - 03/23/18 03:08:02 - 0:07:21 - 1014 source words - csls_knn_10 - Precision at k = 1: 0.098619
INFO - 03/23/18 03:08:02 - 0:07:21 - 1014 source words - csls_knn_10 - Precision at k = 5: 0.295858
INFO - 03/23/18 03:08:02 - 0:07:21 - 1014 source words - csls_knn_10 - Precision at k = 10: 0.690335
(0, 10000, 128)
(128, 10000, 128)
(256, 10000, 128)
(384, 10000, 128)
(512, 10000, 128)
(640, 10000, 128)
(768, 10000, 128)
(896, 10000, 128)
(1024, 10000, 128)
(1152, 10000, 128)
(1280, 10000, 128)
(1408, 10000, 128)
(1536, 10000, 128)
(1664, 10000, 128)
(1792, 10000, 128)
(1920, 10000, 128)
(2048, 10000, 128)
Traceback (most recent call last):
  File "unsupervised.py", line 135, in <module>
    evaluator.all_eval(to_log)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/evaluation/evaluator.py", line 192, in all_eval
    self.dist_mean_cosine(to_log)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/evaluation/evaluator.py", line 172, in dist_mean_cosine
    s2t_candidates = get_candidates(src_emb, tgt_emb, _params)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1513627406021_70260/MUSE/src/dico_builder.py", line 39, in get_candidates
    scores = emb2.mm(emb1[i:min(n_src, i + bs)].transpose(0, 1)).transpose(0, 1)
ValueError: result of slicing is an empty tensor

**Comment by glample** [comment]
Oh I did not realize your embeddings file was that small. Are you sure about this? You should have more than 1962 words. Anyway, if that's the case you indeed will want to replace the `10000` in the code by something smaller, like `1500`.
Can you try to add `--dico_max_rank 1500` in your command?
Check also: https://github.com/facebookresearch/MUSE/search?utf8=%E2%9C%93&q=10000&type=
