### ISSUE TITLE
Evaluation dataset for table-2 in "word translation without parallel data" paper

### ISSUE THREAD

**Issue by alankarj** [facebookresearch/MUSE#32]
What was the evaluation set used for table-2, both for results on Wacky (top 7 rows) and Wiki (bottom 2 rows)?

**Comment by glample** [comment]
We found the Wacky data here: http://clic.cimec.unitn.it/~georgiana.dinu/down/

**Comment by alankarj** [comment]
So, for all the 9 rows in table-2, the evaluation dataset from above link was used?

**Comment by glample** [comment]
Yes

**Comment by alankarj** [comment]
Thanks! Closing.
