### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by AllanZheng** [facebookresearch/MUSE#33]
Hi, I am new to deep learning and I got these errors shown on below when I have already installed Faiss,pytorch,cuda and anaconda.

```
Failed to load GPU Faiss: No module named _swigfaiss_gpu
Faiss falling back to CPU-only.
Impossible to import Faiss library!! Switching to standard nearest neighbors search implementation, this will be significantly slower.

Traceback (most recent call last):
  File "unsupervised.py", line 80, in <module>
    assert not params.cuda or torch.cuda.is_available()
AssertionError

```

**Comment by sbmaruf** [comment]
First of all, are you using any gpu?
if not then while running unsupervised.py please set the flag '--cuda' to 'false'.

Also if you are using gpu then install faiss-gpu in anaconda package to run rhe nearest neighbour search faster.
