### ISSUE TITLE
EN-EO dictionary

### ISSUE THREAD

**Issue by ccsasuke** [facebookresearch/MUSE#34]
Hi,

It seems I could not find the EN-EO dictionary in the list of released dictionaries to reproduce Table 1 results. Are the Esperanto dictionaries released?

Thanks.

**Comment by xiaoleihuang** [comment]
@aconneau Hi, could you also explain the differences between *0-5000.txt and *5000-6500.txt?
Thanks!

**Comment by glample** [comment]
The first is the training set, the second is used for evaluation.

**Comment by KamenBrestnichki** [comment]
Hi @aconneau,

Thank you for open-sourcing all the dictionaries. The links to the EN-EO dictionaries don't seem to work anymore and are not included in the `get_evaluation.sh` bash script. Are they available at another place?

Best wishes,
Kamen

**Comment by glample** [comment]
Hi,

Can you try this link? https://dl.fbaipublicfiles.com/arrival/dictionaries.tar.gz

**Comment by KamenBrestnichki** [comment]
Hi Guillaume,

Thank you for getting back to me so swiftly! The link works, but unfortunately the En-Eo dictionary doesn't seem to be present among the dictionaries in that archive. Do you have an idea of where those could be available?

Thanks,
Kamen

**Comment by glample** [comment]
Mmm if this is not there I really don't know, that was a long time ago and I think we found some small dictionary online, I can't remember :/

**Comment by KamenBrestnichki** [comment]
Hey Guillaume,

Thank you for your time! If you happen to remember, please let me know. I will close the issue now.

Best,
Kamen
