### ISSUE TITLE
About Multilingual word embeddings

### ISSUE THREAD

**Issue by tperl** [facebookresearch/MUSE#36]
Hi,

I downloaded from the Multilingual word Embeddings, embeddings for english and spanish.

If I understand correctly the embeddings for similar words (like good and bueno) , however, when I calculate the cosine similarity between their embeddings I get a smaller value, around 0.15 and for distance words (like bad and bueno) I get the same value.

Should the aligned embeddings have high cosing similarity? am I missing something?

**Comment by glample** [comment]
Hi,

Yes, they should have a high cosine similarity. At least, "good" should have a higher cosine similarity with "bueno" than for almost every other Spanish word. Do you observe this is not the case?
It is not impossible that the highest cosine similarity of target words is only 0.15, even though in our observations they are more around 0.5, 0.6 or something.

**Comment by tperl** [comment]
Thanks for the reply! The issue was in my code. Now I get 0.5,0.6 similarity for close words.
