### ISSUE TITLE
Error with binary fasttext embeddings

### ISSUE THREAD

**Issue by crypotex** [facebookresearch/MUSE#37]
I trained fastText embeddings, all basic commands:
./fasttext cbow -input cleaned.et -thread 16 -dim 300 -output mdl.skip.et
./fasttext cbow -input cleaned.en -thread 16 -dim 300 -output mdl.skip.en

Now I wanted to train supervised MUSE, code:
python unsupervised.py --src_lang et --tgt_lang en --src_emb mdl.skip.et.bin --tgt_emb  mdl.skip.en.bin --export pth --exp_name eten-skip-300 --emb_dim 300 

I get the following stacktrace:
INFO - 04/13/18 09:24:37 - 0:00:00 - The experiment will be stored in /gpfs/hpchome/b02166/thesis/upd_muse/MUSE/dumped/eten-skip-300/c346kmebk8
Traceback (most recent call last):
  File "supervised.py", line 69, in <module>
    src_emb, tgt_emb, mapping, _ = build_model(params, False)
  File "/gpfs/hpchome/b02166/thesis/upd_muse/MUSE/src/models.py", line 46, in build_model
    src_dico, _src_emb = load_embeddings(params, source=True)
  File "/gpfs/hpchome/b02166/thesis/upd_muse/MUSE/src/utils.py", line 402, in load_embeddings
    return load_bin_embeddings(params, source, full_vocab)
  File "/gpfs/hpchome/b02166/thesis/upd_muse/MUSE/src/utils.py", line 369, in load_bin_embeddings
    assert embeddings.size() == (len(words), params.emb_dim)
AssertionError

So there is assertionerror in utils.py file load_bin_embeddings, in assertion assert embeddings.size() == (len(words), params.emb_dim). What am I doing wrong here?

**Comment by glample** [comment]
Hi,

There was indeed a small bug (which appeared when fastText is trained with ngrams and not without ngrams like in a word2vec setting). This commit was designed to handle the bug:
https://github.com/facebookresearch/MUSE/commit/6e0b460549e4963e12347214deca5879fd0fc644

Are you using the latest version? Otherwise, maybe check that the dimension of your embeddings is `300`. Otherwise, can you print and copy here the value of `(len(words), params.emb_dim)` and of `embeddings.size()`?

**Comment by crypotex** [comment]
Yes, thank you, it trains now. I want to get the OOV words translated (there is issue #13 , but I cannot get  embeddings described there).

Is there a way to get out binaries as well ? The output is torch.save(), but I was wondering if it is possible to get the binaries that fasttext(python library or gensim version) ? Is there way to transform it into bin format ?

**Comment by glample** [comment]
For now this is not possible, but this is definitely something we were planning to do at some point. Applying the rotation matrix to every word embedding and ngram embedding in the fastText binary (i.e. the entire input matrix) should do the trick. I don't know if the fastText API allows it. It looks like the API has a "save_model" functionality, but I don't know if you can modify the components of a model easily.

Unfortunately I won't have time to look at this anytime soon but if you want to try I can help you integrating it into MUSE.

**Comment by crypotex** [comment]
I do not have time as well right now, but maybe if I have time over the summer.
