### ISSUE TITLE
Running with unknown languages (how to disable eval)

### ISSUE THREAD

**Issue by viking-sudo-rm** [facebookresearch/MUSE#40]
Hi,

I'm running the unsupervised alignment network on two sets of embeddings, one of which is in an undeciphered language.

I don't really care about the part of the training code that does evaluation against built-in dictionaries, since that isn't really well-defined for my application. Thus, I've tried running unsupervised.py with the default values (es-en) even though my embeddings are in Latin and an unknown language.

This works for the first epoch, but then it gives me the following error message after the epoch finishes and it tries to enter the evaluation code:
Traceback (most recent call last):
  File "unsupervised.py", line 137, in <module>
    evaluator.all_eval(to_log)
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/evaluation/evaluator.py", line 190, in all_eval
    self.word_translation(to_log)
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/evaluation/evaluator.py", line 94, in word_translation
    method=method
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/evaluation/word_translation.py", line 92, in get_word_translation_accuracy
    assert dico[:, 0].max() < emb1.size(0)
IndexError: trying to index 2 dimensions of a 0 dimensional tensor

Any idea what could be going wrong? Or how I could just disable the part of the evaluation that is causing these issues? I have tried commenting out some lines in the code, but this always leaves me with other errors. I would prefer a cleaner solution.

Thanks!

**Comment by glample** [comment]
The Voynich manuscript is difficult because the amount of monolingual data is very small. But here you have no dictionary as you say so you cannot evaluate anything. In the `all_eval ` function of `evaluator.py` you can probably just comment out the line `self.word_translation(to_log)` and it should be fine.

**Comment by viking-sudo-rm** [comment]
Thanks for your suggestion! It is true that the Voynich is a pretty small text, but I'm interested in seeing what happens for some of the most frequently occurring words.

I've tried commenting out `self.word_translation(to_log)` and I am left with an error thrown from `self.dist_mean_cosine(to_log)`:

INFO - 04/17/18 12:25:02 - 0:07:29 - Cross-lingual word similarity score average: nan
Traceback (most recent call last):
  File "unsupervised.py", line 137, in <module>
    evaluator.all_eval(to_log)
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/evaluation/evaluator.py", line 192, in all_eval
    self.dist_mean_cosine(to_log)
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/evaluation/evaluator.py", line 172, in dist_mean_cosine
    s2t_candidates = get_candidates(src_emb, tgt_emb, _params)
  File "/gpfs/loomis/home.grace/fas/frank/wcm24/voynich2vec/MUSE/src/dico_builder.py", line 38, in get_candidates
    scores = emb2.mm(emb1[i:min(n_src, i + bs)].transpose(0, 1)).transpose(0, 1)
ValueError: result of slicing is an empty tensor

I'm a little confused about what cosine distance this next line is evaluating, but it seems like something that I shouldn't be commenting out (?). Indeed, when I try to, I get a bunch of `KeyErrors` since the value it finds is being referenced elsewhere.

**Comment by viking-sudo-rm** [comment]
When I run it with `--dico_build S2T`, I get the same "result of slicing is an empty tensor" error message.

**Comment by viking-sudo-rm** [comment]
Also, I should have mentioned before that the way I am running `unsupervised.py` is:
```python
python unsupervised.py --src_emb ../models/voynich.vec --tgt_emb ../models/secretaSecretorum.vec --n_refinement 5 --emb_dim 100 --dis_most_frequent 100 --dico_build S2T
```

**Comment by viking-sudo-rm** [comment]
Update:
The issue came from the fact that `_params.dico_max_rank` is being reset in line 169 of src/evaluate/evaluator.py:
```python
_params.dico_max_rank = 10000
```
I commented this out so that `_params.dico_max_rank` is still set to 0, and the error was resolved.
