### ISSUE TITLE
Why use adversarial training in the original paper?

### ISSUE THREAD

**Issue by bdqnghi** [facebookresearch/MUSE#41]
Hi, this question is not related to the code implementation itself but more about the detail of the original paper, since I don't know that if there is a better place to ask then I put the question here.

Since from the Orthogonal Procrustes problem, we know that W = SVD(X*Y-transpose). Why not just compute the SVD of (X*Y-transpose) instead of introducing the adversarial training approach?

**Comment by glample** [comment]
Because here X and Y have to be aligned matrices, and you can only have aligned matrices if you have a bilingual lexicon. But if you are in the fully unsupervised setting, you just don't have access to such lexicon and you cannot directly apply the Procrustes solution.

**Comment by bdqnghi** [comment]
I see, thanks :)
