### ISSUE TITLE
The usage of embeddings during evaluation

### ISSUE THREAD

**Issue by cTFe** [facebookresearch/MUSE#48]
Hi, I have a quick question about embeddings used during the evaluation.
In README.md, the crosslingual evaluation `python evaluate.py --src_lang en --tgt_lang es --src_emb data/wiki.en-es.en.vec --tgt_emb data/wiki.en-es.es.vec --max_vocab 200000` means use the pretrained embeddings or first normalized then mapped to the source target embeddings as processed in `trainer.export()`? 

It seems that the monolingual evaluation uses pretrained embeddings in `data/wiki.en.vec` which is different from `data/wiki.en-es.en.vec`. If crosslingual evaluation uses embeddings of exported version, why does the code `src_emb = self.mapping(self.src_emb.weight).data.cpu().numpy()` in `evaluator.py` do mapping once again?
Am I getting anything wrong?

**Comment by cTFe** [comment]
Oh is it because `self.mapping` is first initialized as diagonal matrix so that in crosslingual evaluation, actually it does nothing to the exported embeddings?

**Comment by glample** [comment]
`evaluate.py` will load the embeddings, and do the L2 normalization automatically to compute the cosine distance. As you noticed, the mapping will be set to the identity by default when you load `evaluate.py`, so the embeddings won't be modified:
