### ISSUE TITLE
embedding files not generated.

### ISSUE THREAD

**Issue by NewInfinite007** [facebookresearch/MUSE#53]
After running the supervised alignment script, the embedding vectors are not dumped in the dump directory. Instead i get this error at the end of last refinement iteration : 

flags:
n_refinement = 1
export txt
cuda False

langs:
hi-en

```
INFO - 06/04/18 15:26:33 - 3:15:50 - End of iteration 1.
                                     
                                     
INFO - 06/04/18 15:26:33 - 3:15:50 - * Reloading the best model from /home/ravi/muse/MUSE/dumped/debug/n31qnn6tl6/best_mapping.pth ...
INFO - 06/04/18 15:26:33 - 3:15:50 - Reloading all embeddings for mapping ...
INFO - 06/04/18 15:26:50 - 3:16:08 - Loaded 158016 pre-trained word embeddings.
INFO - 06/04/18 15:30:55 - 3:20:12 - Loaded 2519370 pre-trained word embeddings.
Traceback (most recent call last):
  File "./MUSE/supervised.py", line 109, in <module>
    trainer.export()
  File "/home/myDir/muse/MUSE/src/trainer.py", line 252, in export
    params.tgt_dico, tgt_emb = load_embeddings(params, source=False, full_vocab=True)
  File "/home/myDir/muse/MUSE/src/utils.py", line 406, in load_embeddings
    return read_txt_embeddings(params, source, full_vocab)
  File "/home/myDir/muse/MUSE/src/utils.py", line 310, in read_txt_embeddings
    embeddings = torch.from_numpy(embeddings).float()
RuntimeError: $ Torch: not enough memory: you tried to allocate 2GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.c:218
```
can anyone help me out with this?
 Thanks in advance.

**Comment by glample** [comment]
It looks like you don't have enough memory. How much RAM do you have on your computer? The system failed by trying to allocate 2GB of RAM.

**Comment by NewInfinite007** [comment]
I am running it on a google cloud instance with 16GB of RAM.

**Comment by glample** [comment]
15GB of RAM should be enough to load all the 2519370 embeddings you have in your text file. Maybe you have some other things running on your server?

I'll close the issue for now, as the problem seems to be related to the amount of RAM you have and that 2GB are missing, so there is nothing much we can do, but feel free to re-open.

**Comment by ldmichel** [comment]
I have the same problem even if I still have 7GB left to spare.
---------------------                                     
INFO - 04/11/19 02:37:51 - 3:24:10 - * Reloading the best model from /home/michelangelolinu/Dokumente/MUSE-master/dumped/debug/njmekinfn6/best_mapping.pth ...
INFO - 04/11/19 02:37:51 - 3:24:10 - Reloading all embeddings for mapping ...
INFO - 04/11/19 02:40:02 - 3:26:21 - Loaded 2519370 pre-trained word embeddings.
Traceback (most recent call last):
  File "supervised.py", line 112, in <module>
    trainer.export()
  File "/home/michelangelolinu/Dokumente/MUSE-master/src/trainer.py", line 251, in export
    params.src_dico, src_emb = load_embeddings(params, source=True, full_vocab=True)
  File "/home/michelangelolinu/Dokumente/MUSE-master/src/utils.py", line 406, in load_embeddings
    return read_txt_embeddings(params, source, full_vocab)
  File "/home/michelangelolinu/Dokumente/MUSE-master/src/utils.py", line 309, in read_txt_embeddings
    embeddings = np.concatenate(vectors, 0)
MemoryError
