### ISSUE TITLE
Cuda out of memory during evaluation

### ISSUE THREAD

**Issue by rjuge** [facebookresearch/MUSE#57]
Hi,
I am trying to align pretrained english and french embeddings from fasttext in the unsupervised way but I encounter the following issue:
```
INFO - 06/13/18 14:39:34 - 0:16:16 - Found 2940 pairs of words in the dictionary (1499 unique). 3 other pairs contained at least one unknown word (0 in lang1, 3 in lang2)
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "unsupervised.py", line 139, in <module>
    evaluator.all_eval(to_log)
  File "/home/rjuge/Fortia/MUSE/src/evaluation/evaluator.py", line 215, in all_eval
    self.word_translation(to_log)
  File "/home/rjuge/Fortia/MUSE/src/evaluation/evaluator.py", line 119, in word_translation
    dico_eval=self.params.dico_eval
  File "/home/rjuge/Fortia/MUSE/src/evaluation/word_translation.py", line 133, in get_word_translation_accuracy
    scores.sub_(average_dist1[dico[:, 0]][:, None] + average_dist2[None, :])
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
```
I use the default english-french dictionary. My GPU is a GTX 1060.
Is there a way to reduce the GPU load during the evaluation? 
Thanks.

**Comment by glample** [comment]
Hi,

Sorry for the delay. How much memory do you have available for the experiment? Also, what is your vocabulary size (both for training and evaluation)?

**Comment by rjuge** [comment]
Hi @glample ,

Basically, my config is Ubuntu 16.04 with 32GB of RAM and 6GB on GPU.
I use the english and french fastText pretrained embeddings (wiki-news-300d-1M-subword.vec & cc.fr.300.vec) and keep the default value of max_vocab (200k).
I want to align them in the unsupurvised way so no dict for training and I use the default one for evaluation. 
Here is my [train.log](https://github.com/facebookresearch/MUSE/files/2140490/train.log).


Thanks!

**Comment by glample** [comment]
Mmm I'm surprised because this part of the code is just creating a matrix of size (200000, 3000) and it should easily fit in memory. If you pause the code just before the line that breaks what is the memory used? Maybe can you try to use 100000 or 50000 words instead of 200000 for full vocab?

**Comment by rjuge** [comment]
So when I pause before it breaks, the process uses 2.8GB of RAM and 4GB of GPU. 
The breaking line is [this one](https://github.com/facebookresearch/MUSE/blob/master/src/evaluation/word_translation.py#L133). After pausing, manually running `average_dist1[dico[:, 0]][:, None] + average_dist2[None, :]` gives me the `RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58` error.

**Comment by rjuge** [comment]
Yeah actually I tried to replace the breaking line with this workaround and it reduces the memory print. 
Thanks @glample !

**Comment by glample** [comment]
Updated in https://github.com/facebookresearch/MUSE/commit/03af0aeb82ef43858be1dd35ef50beb45cac9a9b
