### ISSUE TITLE
Error during training en-ha (Hausa)

### ISSUE THREAD

**Issue by xiaoleihuang** [facebookresearch/MUSE#60]
I am using English and Hausa embeddings from FastText. Yet, I got the following error.
```
Traceback (most recent call last):
  File "supervised.py", line 99, in <module>
    evaluator.all_eval(to_log)
  File "PATH/MUSE/src/evaluation/evaluator.py", line 219, in all_eval
    self.dist_mean_cosine(to_log)
  File "PATHMUSE/src/evaluation/evaluator.py", line 199, in dist_mean_cosine
    t2s_candidates = get_candidates(tgt_emb, src_emb, _params)
  File "PATH/MUSE/src/dico_builder.py", line 38, in get_candidates
    scores = emb2.mm(emb1[i:min(n_src, i + bs)].transpose(0, 1)).transpose(0, 1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by xiaoleihuang** [comment]
After I replaced the pretrained vector file by my own trained model, then it worked... The pre-trained Hausa model from fastText might have typos.

**Comment by Pzoom522** [comment]
Hi @xiaoleihuang , since you've attempted English-Hausa alignment, may I ask where did you obtain the dictionary for evaluation please? Many thanks!

**Comment by xiaoleihuang** [comment]
@Pzoom522 Hi, Xutan, I don't remember the details. But I cited a bilingual dictionary resource in my previous paper (https://www.aclweb.org/anthology/D19-1672.pdf), which has a link to the resource in the reference. You can request the dictionary from the authors: 
Leanne Rolston and Katrin Kirchhoff. 2016. Collection of bilingual data for lexicon transfer learning. Technical report, Technical Report UW-EE-2016-0001.

**Comment by Pzoom522** [comment]
Wow, thanks a lot for your information! :bouquet:
