### ISSUE TITLE
How to save mapped embeddings in the supervised setting?

### ISSUE THREAD

**Issue by bdqnghi** [facebookresearch/MUSE#63]
In the unsupervised setting, in the dumped folder, there are new versions of the mapped embeddings. But in the supervised setting, there is none, how can I enable that?

**Comment by glample** [comment]
There is a `--export` parameter for both supervised and unsupervised training. If you set `--export txt` it should export the embeddings to a text file.

**Comment by bdqnghi** [comment]
I see, thanks
