### ISSUE TITLE
Assertion error in unsupervised.py

### ISSUE THREAD

**Issue by varshit97** [facebookresearch/MUSE#68]
INFO - 07/25/18 12:19:28 - 0:00:04 - ----> ADVERSARIAL TRAINING <----
INFO - 07/25/18 12:19:28 - 0:00:04 - Starting adversarial training epoch 0...
Traceback (most recent call last):
  File "unsupervised.py", line 118, in <module>
    trainer.dis_step(stats)
  File "/home/varshit97/MUSE/src/trainer.py", line 90, in dis_step
    x, y = self.get_dis_xy(volatile=True)
  File "/home/varshit97/MUSE/src/trainer.py", line 61, in get_dis_xy
    assert mf <= min(len(self.src_dico), len(self.tgt_dico))
AssertionError

How can I fix this error?
I have source and target .vec files and I am trying to generate cross lingual embeddings.

**Comment by glample** [comment]
What are the sizes of your source and target dictionaries?
Can you replace line 60 with:
`mf = max(self.params.dis_most_frequent, min(len(self.src_dico), len(self.tgt_dico)))`
and see if this helps?

**Comment by varshit97** [comment]
@glample I get the same error even after replacing line 60.
size of source and target dictionaries are 5356 and 3192.

**Comment by glample** [comment]
I'm sorry, I meant to say:
`mf = min(self.params.dis_most_frequent, min(len(self.src_dico), len(self.tgt_dico)))`

The problem here is that the model is trying to sample words from the `self.params.dis_most_frequent` most frequent words, but if this value is bigger than your dictionaries it will raise an error.

**Comment by varshit97** [comment]
@glample This worked :D 
Thanks
And one more thing
In the unsupervised technique after the training is done, the model is being evaluated with some cross lingual dictionaries. What if I need to generate the cross lingual embeddings for a language-pair which do not have a cross lingual dictionary?

Traceback (most recent call last):
  File "unsupervised.py", line 139, in <module>
    evaluator.all_eval(to_log)
  File "/home/varshit97/MUSE/src/evaluation/evaluator.py", line 217, in all_eval
    self.word_translation(to_log)
  File "/home/varshit97/MUSE/src/evaluation/evaluator.py", line 120, in word_translation
    dico_eval=self.params.dico_eval
  File "/home/varshit97/MUSE/src/evaluation/word_translation.py", line 94, in get_word_translation_accuracy
    dico = load_dictionary(path, word2id1, word2id2)
  File "/home/varshit97/MUSE/src/evaluation/word_translation.py", line 50, in load_dictionary
    assert os.path.isfile(path)
AssertionError

**Comment by glample** [comment]
If the language you are working on does not provide dictionaries, you won't be able to evaluate the model. Of course you can still generate cross-lingual embeddings / alignments, but you won't be able to evaluate the quality of those. To run the model without evaluation, you can simply disable the lines that require a dictionary for the evaluation (for instance, comment out line 217 in evaluator.py: `self.word_translation(to_log)`).
