### ISSUE TITLE
Decreasing P@1 during supervised training

### ISSUE THREAD

**Issue by rjuge** [facebookresearch/MUSE#70]
Hello guys,

I am trying to align English and French fasttext embeddings in the supervised way. I have around 72 000 of them for each language and they are 100-dimensional. My training dictionary contains around 1500 pairs. To check how good I can stick to this dictionary, I also use it as a validation dictionary. 
The problem is that the P@1 is constantly decreasing. Training log is [here](https://github.com/facebookresearch/MUSE/files/2244813/train.log).

Do you think that my training dict is too small? Or any other idea?

Thanks a lot

**Comment by aconneau** [comment]
Hi,

so your training dict and your valid dict are the same? If that's the case, the fact that the first iteration (20.4%) leads to a significantly better accuracy is not surprising as the mapping W is directly optimized for the valid dict. For epoch >= 2 (best= 15.9% accuracy at epoch 2 in your case), the Procrustes uses a synthetic dictionary which is then different from your validation set.

I think in this case, the decrease from epoch 2 onwards is artificial (although we've sometimes observed a small decrease even in classic cases): at each epoch, the synthetic dictionary is created based on the mapping from the previous epoch. In your case, you started with the optimal mapping (best for your valid set) so it's progressively worse as you depart from this. I would try with two distinct train and valid dictionaries to see if you observe the same thing.

Best,
Alexis

**Comment by rjuge** [comment]
Ok I got it, makes sense. 
Thank you,
Rémi
