### ISSUE TITLE
Subword information in MUSE

### ISSUE THREAD

**Issue by dominikabasaj** [facebookresearch/MUSE#71]
Hi!

Do I understand correctly that for know MUSE embeddings do not have properties of fastText embeddings in terms of encoding subword information? In practice it means that I cannot encode words not present in dictionary?

Thank you :)

**Comment by glample** [comment]
Your understanding is correct, MUSE doesn't use subword information.

However, if you have an unknown word, you can still create an embedding for it using fastText, and align the resulting embedding with MUSE :)
