### ISSUE TITLE
Understanding of CSLS

### ISSUE THREAD

**Issue by cTFe** [facebookresearch/MUSE#77]
Hi, I am confused by how CSLS is computed. I understand that N_T(Wx_s) finds the nearest neighbors in target language for mapped source words. But does N_S(y_t) means finding the nearest neighbors in the source language for target words? The embeddings of y_t is not in the same space as the embeddings of x_i, so I was wondering if the definition of N_S(y_t) makes sense. Thank you!

**Comment by glample** [comment]
Hi, this is a good point. In practice, it should not be "N_S(y_t)" but more "N_{WS}(y_t)", i.e. we look at the nearest neighbors of target words in the mapped source embeddings. In the end, everything is happening in the target space. The notation is wrong here, but in practice it is "N_{WS}(y_t)" that we compute (so the code implementation is correct, and the notation is not very accurate).

**Comment by cTFe** [comment]
That makes sense. I'll check out the codes. Thanks!
