### ISSUE TITLE
subword embedings

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/MUSE#79]
Hi, Could I use MUSE to train BPE words(Sennrich et al. 2015.)?  Does the evaluation words（path specified by parameter dico_eval ） also need to be a list of BPE word, when training bpe words? How is the performance compared to the use of words?  Thank you much .

**Comment by glample** [comment]
You can train BPE embeddings with fastText and align them with MUSE, that's definitely possible. Then, you can use MUSE with BPE as if you were using words. There will be some unknown words in the dictionary though (words in the dictionary that have been split and that become unknown). MUSE will simply ignore them. This is fine, but the evaluation compared to words is not straightforward as the vocabulary will be different, so you have to be careful about this.

**Comment by liujiqiangresearch** [comment]
Appreciated your reply so quickly! I got it . Thank you !
