### ISSUE TITLE
unsupervised.py - warnings for volatile and dimension error

### ISSUE THREAD

**Issue by gojoego** [facebookresearch/MUSE#80]
I'm running the following command on the nightly build of PyTorch:

`python unsupervised.py --src_lang en --tgt_lang es --src_emb data/wiki.en.vec --tgt_emb data/wiki.es.vec --n_refinement 5 --cuda=False --exp_name=Test2`

Doing so produces a series of warnings and an index error:
```
`INFO - 10/10/18 21:54:05 - 0:01:40 - Starting adversarial training epoch 0...
/home/joe/MUSE/src/trainer.py:69: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  src_emb = self.src_emb(Variable(src_ids, volatile=True))

/home/joe/MUSE/src/trainer.py:70: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  tgt_emb = self.tgt_emb(Variable(tgt_ids, volatile=True))

/home/joe/MUSE/src/trainer.py:71: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  src_emb = self.mapping(Variable(src_emb.data, volatile=volatile))

/home/joe/MUSE/src/trainer.py:72: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  tgt_emb = Variable(tgt_emb.data, volatile=volatile)

Traceback (most recent call last):
  File "unsupervised.py", line 117, in <module>
    trainer.dis_step(stats)
  File "/home/joe/MUSE/src/trainer.py", line 93, in dis_step
    stats['DIS_COSTS'].append(loss.data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

I know that newer versions of PyTorch jettisoned the volatile option, but I'm not sure where add in the `torch.no_grad()` alternative.  Also is the IndexError related to this or is indicative of another issue?

Thanks,

Joe

**Comment by gojoego** [comment]
Answered my own question.

**Comment by glample** [comment]
Hello.

Sorry for the delay. What was the solution for you? Replacing `stats['DIS_COSTS'].append(loss.data[0])` with `stats['DIS_COSTS'].append(loss.item())`? If so I will push a fix as probably other users will face this issue.
