### ISSUE TITLE
max_vocab argument is not enforced

### ISSUE THREAD

**Issue by niless** [facebookresearch/MUSE#86]
Even though the default value is 200000,  using supervised option with wiki.en.vec from fastText of size 2M, I got the same size output and not the most frequent ones as it used to be.

**Comment by glample** [comment]
Hi,

Do you mean that the output file has the same number of words than the original one, and not 200k? This is normal. The 200k just means that the model will only load 200k words to perform the alignment and the evaluation. But once the alignment is learned, it can be used to align any words, including the ones that are not in the most 200k frequent ones, and that's what the code does.

**Comment by niless** [comment]
Thanks for the explanation. Previous version of the code would output only 200K so that was my expectation but it seems like it is an internal setting now and accordingly, it can be explained better in the argument's description.
