### ISSUE TITLE
How to use the aligned vectors?

### ISSUE THREAD

**Issue by jamsheer2u** [facebookresearch/MUSE#9]
Is it possible to provide some examples on how to use the monolingual aligned vectors (unsupervised) to generate translations? I have got the aligned vectors for Malayalam-Hindi, it would be helpful, if I can get an example how I can proceed further.

**Comment by aconneau** [comment]
@jamsheer2u you need to implement a function that takes a Malayalam word as input, and compute the cosine similarity between this word and all the words in Hindi. Then take the word in Hindi that has the highest cosine with the input Malayalam word.
We will provide a demo ipython notebook to load some word vectors and play with it.

**Comment by jamsheer2u** [comment]
Thanks, I loaded the vectors using gensim word2vec keyedvectors and got
some success.

Do you have any sample code that uses Neural Machine Translation?

**Comment by glample** [comment]
Hi @jamsheer2u,
This repo is for embeddings only. But we will probably open-source code for unsupervised NMT in the future.

**Comment by naman-agrawal** [comment]
How to use  best_mappings.pth  generated by unsupervised.py on english<---->spanish language pairs to get a dictionary/list of words.

**Comment by glample** [comment]
What you could do is start the `supervised.py` code by providing your source and target embeddings, then just after this line: https://github.com/facebookresearch/MUSE/blob/master/supervised.py#L66
you can modify the `mapping` attribute of the model to reload your `best_mappings.pth`. You can check this function to see how to do this:
https://github.com/facebookresearch/MUSE/blob/8c41b2e8050cabc0b3d65a6699e8fb0eb151b862/src/trainer.py#L230

Something like this should work:
```python
to_reload = torch.from_numpy(torch.load('your_path/best_mappings.pth'))
W = trainer.mapping.weight.data
assert to_reload.size() == W.size()
W.copy_(to_reload.type_as(W))
```

Then, by simply calling `trainer.build_dictionary()`, `trainer.dico` will contain the dictionary you are looking for.

**Comment by naman-agrawal** [comment]
thank you!

**Comment by fratamico** [comment]
After doing unsupervised training, are the output vectors produced the aligned ones? Or do I need to also use the .pth file to align them.

I'm trying to both build a dictionary and compute the distance between the pairs.

**Comment by glample** [comment]
Yes, the output vectors are aligned and you can directly use that.
