### ISSUE TITLE
How to evaluate the training result?

### ISSUE THREAD

**Issue by CrystalWLH** [facebookresearch/MUSE#90]
Hi all,
I tried to  use the Chinese and Tibetan word embeddings provided by FastText to train in an unsupervised way. The training commands are as follows:

-  python3 unsupervised.py --src_lang zh --tgt_lang bo --src_emb data/cc.zh.300.vec --tgt_emb data/cc.bo.300.vec --n_refinement 5  --emb_dim 300 --n_epochs 10 --epoch_size 1000000 --batch_size 32 --dis_most_frequent 60000 

But I don't know how to evaluate my training results is good or bad? Any help?

**Comment by glample** [comment]
Hi,

You will need to have a zh-bo validation dictionary here to evaluate your results. We provide 110 dictionaries for some language pairs, but it's mainly en-XX or XX-en directions, or some pairs of European languages. In your case, you will have to generate a new small dictionary.

**Comment by CrystalWLH** [comment]
I get it. Thank you. But I still have a doubt about it. I find the Tibetan word embedding provided by FastText  is based on the syllable level rather than the word level. I want to know if we can align  the word embedding of Tibetan syllables and the word embedding of Chinese words. If we can, is it true that the dictionary I generated is a Chinese word corresponding to a Tibetan syllable?

**Comment by glample** [comment]
Mmm aligning syllables to words will be difficult. Maybe the dataset on which the Tibetan embeddings were trained was not tokenized in the good way (I really don't know about that), in that case you will have to preprocess it and re-train fastText on it (which should be fast to do as I assume this is not a huge dataset).

**Comment by CrystalWLH** [comment]
I would like to ask the question further. I generated a zh-bo dictionary, but I found the evaluate results is so bad. 
For example: nn - Precision at k = 10: 0.151515，csls_knn_10 - Precision at k = 10: 0.129870
I think my zh-bo dictionary and the task do not match. So, I want to know if there are other metrics without dictionary? Such as mean_cosine-csls_knn_10-S2T-10000 and so on.
