### ISSUE TITLE
I run the unsupervised one with english and chinese, but always get a result of presicion k=10 of 0.

### ISSUE THREAD

**Issue by MaCYbupt** [facebookresearch/MUSE#92]
Do you know why it happens?

**Comment by CrystalWLH** [comment]
I also meet the same problem today, but I can get the results in my previous experiments, ask for answers.

**Comment by MaCYbupt** [comment]
> Hi~I think I find the solution. We should set the parameter "--normalize_embeddings" to center.
> As the official description:
> 
> > By default, the validation metric is the mean cosine of word pairs from a synthetic dictionary built with CSLS (Cross-domain similarity local scaling). For some language pairs (e.g. En-Zh), we recommend to center the embeddings using --normalize_embeddings center.

sorry for not noticing it, thank you.
