### ISSUE TITLE
Assertion error after training unsupervised

### ISSUE THREAD

**Issue by CarbuncleOrigin** [facebookresearch/MUSE#95]
After training or running this:
  python unsupervised.py --src_lang en --tgt_lang tl --src_emb data/wiki.en.vec --tgt_emb data/wiki.tl.vec --n_refinement 5

I get these errors

Traceback (most recent call last):
  File "unsupervised.py", line 139, in <module>
    evaluator.all_eval(to_log)
  File "C:\Users\ZENON\Desktop\new\MUSE-master\src\evaluation\evaluator.py", line 217, in all_eval
    self.word_translation(to_log)
  File "C:\Users\ZENON\Desktop\new\MUSE-master\src\evaluation\evaluator.py", line 120, in word_translation
    dico_eval=self.params.dico_eval
  File "C:\Users\ZENON\Desktop\new\MUSE-master\src\evaluation\word_translation.py", line 92, in get_word_translation_accuracy
    dico = load_dictionary(path, word2id1, word2id2)
  File "C:\Users\ZENON\Desktop\new\MUSE-master\src\evaluation\word_translation.py", line 49, in load_dictionary
    assert os.path.isfile(path)
AssertionError

Any idea why this happens?
note: I've already run the get_evaluation.sh

train info:

INFO - 12/11/18 12:08:09 - 0:00:00 - ============ Initialized logger ============
INFO - 12/11/18 12:08:09 - 0:00:00 - adversarial: True
                                     batch_size: 32
                                     cuda: True
                                     dico_build: S2T
                                     dico_eval: default
                                     dico_max_rank: 15000
                                     dico_max_size: 0
                                     dico_method: csls_knn_10
                                     dico_min_size: 0
                                     dico_threshold: 0
                                     dis_clip_weights: 0
                                     dis_dropout: 0.0
                                     dis_hid_dim: 2048
                                     dis_input_dropout: 0.1
                                     dis_lambda: 1
                                     dis_layers: 2
                                     dis_most_frequent: 75000
                                     dis_optimizer: sgd,lr=0.1
                                     dis_smooth: 0.1
                                     dis_steps: 5
                                     emb_dim: 300
                                     epoch_size: 1000000
                                     exp_id: 
                                     exp_name: debug
                                     exp_path: C:\Users\ZENON\Desktop\new\MUSE-master\dumped\debug\xy8kjg79e0
                                     export: txt
                                     lr_decay: 0.98
                                     lr_shrink: 0.5
                                     map_beta: 0.001
                                     map_id_init: True
                                     map_optimizer: sgd,lr=0.1
                                     max_vocab: 200000
                                     min_lr: 1e-06
                                     n_epochs: 5
                                     n_refinement: 5
                                     normalize_embeddings: 
                                     seed: -1
                                     src_emb: data/wiki.en.vec
                                     src_lang: en
                                     tgt_emb: data/wiki.tl.vec
                                     tgt_lang: tl
                                     verbose: 2
INFO - 12/11/18 12:08:09 - 0:00:00 - The experiment will be stored in C:\Users\ZENON\Desktop\new\MUSE-master\dumped\debug\xy8kjg79e0
INFO - 12/11/18 12:08:35 - 0:00:26 - Loaded 200000 pre-trained word embeddings.
INFO - 12/11/18 12:09:05 - 0:00:56 - Loaded 200000 pre-trained word embeddings.
INFO - 12/11/18 12:09:08 - 0:00:58 - ----> ADVERSARIAL TRAINING <----
                                     
                                     
INFO - 12/11/18 12:09:08 - 0:00:58 - Starting adversarial training epoch 0...
INFO - 12/11/18 12:09:08 - 0:00:59 - 000000 - Discriminator loss: 0.6924 - 230 samples/s
...
INFO - 12/11/18 12:44:38 - 0:36:29 - 996000 - Discriminator loss: 0.5330 - 2209 samples/s
INFO - 12/11/18 12:44:42 - 0:36:33 - ====================================================================
INFO - 12/11/18 12:44:42 - 0:36:33 -                        Dataset      Found     Not found          Rho
INFO - 12/11/18 12:44:42 - 0:36:33 - ====================================================================
INFO - 12/11/18 12:44:42 - 0:36:33 - ====================================================================
INFO - 12/11/18 12:44:42 - 0:36:33 - Monolingual source word similarity score average: nan

**Comment by lihongzheng-nlp** [comment]
@CarbuncleOrigin Hello, right now I met the same problem as you did, how did you solve it?  Did you use **a dictionary** in the unsupervised training? But I guess the dictionary is not needed in unsupervised training, right? I have no dictionary, I only have monolingual embeddings.

**Comment by umeshpant** [comment]
> @CarbuncleOrigin Hello, right now I met the same problem as you did, how did you solve it? Did you use **a dictionary** in the unsupervised training? But I guess the dictionary is not needed in unsupervised training, right? I have no dictionary, I only have monolingual embeddings.

I guess they are using a dictionary for evaluation purpose.
